name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow on pull requests to the main branch

env:
  IMAGE_NAME: my-java-app  # Name of the Docker image
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}  # Docker Hub username
  DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}  # Docker Hub access token

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Java and Maven
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # Build the Maven project
      - name: Build with Maven
        run: mvn clean package

      # Login to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Retrieve the incremental counter
      - name: Get Incremental Counter
        id: counter
        uses: actions/cache@v3
        with:
          path: counter.txt
          key: counter-${{ github.ref }}
          restore-keys: counter-${{ github.ref }}

      # Increment the counter
      - name: Increment Counter
        run: |
          if [ -f counter.txt ]; then
            COUNTER=$(cat counter.txt)
          else
            COUNTER=0
          fi
          COUNTER=$((COUNTER + 1))
          echo $COUNTER > counter.txt
          echo "INCREMENTAL_TAG=$COUNTER" >> $GITHUB_ENV

      # Format the tag as v01, v02, etc.
      - name: Format Tag
        run: |
          FORMATTED_TAG=$(printf "v%02d" $INCREMENTAL_TAG)
          echo "FORMATTED_TAG=$FORMATTED_TAG" >> $GITHUB_ENV

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t $DOCKER_HUB_USERNAME/$IMAGE_NAME:latest .
          docker tag $DOCKER_HUB_USERNAME/$IMAGE_NAME:latest $DOCKER_HUB_USERNAME/$IMAGE_NAME:$FORMATTED_TAG

      # Push the Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker push $DOCKER_HUB_USERNAME/$IMAGE_NAME:latest
          docker push $DOCKER_HUB_USERNAME/$IMAGE_NAME:$FORMATTED_TAG